name: Expire

on:
  schedule:
  - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  expire:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Remove expired IPs
        run: |
          awk -i inplace -v current_time=$(date +%s) '$2 > current_time' suspiciousips/operations
          echo "builddate=$(date -Is)" >> $GITHUB_OUTPUT
          echo "epochdate=$(date +%s)" >> $GITHUB_OUTPUT
          
      - name: Stage files
        run: git add .

      - name: Commit changes
        run: |
          git config --global user.email "support@sitehost.co.nz"
          git config --global user.name "SiteHost NZ"
          git commit -m "Filter expired rate-limits" || echo "Nothing to commit"

      - name: fetch from master
        run: git pull --rebase origin main

      - name: push code to master
        run: git push origin HEAD:main
